server:
  port: 8080

spring:
  profiles:
    active: local

  config:
    import: optional:dotenv:.env # .env 파일 불러오기

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ email, profile ]
            redirect-uri: "http://13.60.13.30.nip.io/login/oauth2/code/{registrationId}"
        provider:
          google:
            user-name-attribute: sub

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/danggeun
    username: postgres
    password: 2327

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

gemini:
  api-key: dummy-key-for-local

#aws:
#  access-key-id: ${AWS_ACCESS_KEY_ID}
#  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
#  region: eu-north-1
#  s3:
#    bucket-name: ${S3_BUCKET_NAME}

file:
  upload-dir: ${FILE_UPLOAD_DIR}
